"""Copy best_skill.md into the Dataverse-skills plugin and open a draft PR.

Usage:
    python -m skillopt.envs.dataverse.scripts.promote \
        --run outputs/dv_data_run_01 \
        --plugin ../Dataverse-skills/.github/plugins/dataverse/skills/dv-data
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
from pathlib import Path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", required=True, help="SkillOpt run output dir (contains best_skill.md)")
    ap.add_argument("--plugin", required=True, help="Target skill directory inside Dataverse-skills clone")
    ap.add_argument("--branch", default="", help="Branch name to push (default: skillopt/<skill>-<run>)")
    args = ap.parse_args()

    best = Path(args.run) / "best_skill.md"
    if not best.exists():
        raise SystemExit(f"best_skill.md not found in {args.run}")

    dest = Path(args.plugin) / "SKILL.md"
    plugin_repo = next((p for p in dest.parents if (p / ".git").exists()), None)
    if plugin_repo is None:
        raise SystemExit(f"could not find a git repo containing {dest}")
    skill_name = dest.parent.name
    branch = args.branch or f"skillopt/{skill_name}-{Path(args.run).name}"

    subprocess.check_call(["git", "-C", str(plugin_repo), "checkout", "-b", branch])
    shutil.copy(best, dest)
    subprocess.check_call(["git", "-C", str(plugin_repo), "add", str(dest.relative_to(plugin_repo))])
    subprocess.check_call([
        "git", "-C", str(plugin_repo), "commit",
        "-m", f"skill({skill_name}): SkillOpt-optimized update from {Path(args.run).name}",
    ])
    subprocess.check_call(["git", "-C", str(plugin_repo), "push", "-u", "origin", branch])
    # Open a draft PR
    subprocess.check_call([
        "gh", "pr", "create", "--draft",
        "--title", f"skill({skill_name}): SkillOpt-optimized update",
        "--body", f"Generated by SkillOpt run `{Path(args.run).name}`. Eval deltas in run output.",
        "--repo", "microsoft/Dataverse-skills",
    ], cwd=str(plugin_repo))


if __name__ == "__main__":
    main()
